apiVersion: v2
name: ndb-operator
description: A Helm chart for Nutanix Database Kubernetes Operator
type: application
version: 0.0.5
appVersion: "v0.0.5"
maintainers:
  - name: akshmish
    email: akshay.mishra@nutanix.com
  - name: shenoypritika
    email: pritika.shenoy@nutanix.com
  - name: krunal-jhaveri
    email: krunal.jhaveri@nutanix.com
  - name: manavrajvanshi
    email: manav.rajvanshi@nutanix.com
  - name: yash-ntnx
    email: yashesh.mankad@nutanix.com
icon: https://www.nutanix.com/content/dam/nutanix/global/icons/products/svg/Nutanix-Era-40.svg
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "MSSQL Provisioning"
    - kind: added
      description: "Ability to provide profile information"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: |
    - name: akshmish
      email: akshay.mishra@nutanix.com
    - name: shenoypritika
      email: pritika.shenoy@nutanix.com
    - name: krunal-jhaveri
      email: krunal.jhaveri@nutanix.com
    - name: manavrajvanshi
      email: manav.rajvanshi@nutanix.com
    - name: yash-ntnx
      email: yashesh.mankad@nutanix.com
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Basic Install
  artifacthub.io/prerelease: "true"
